---
editor: 
  markdown: 
    wrap: 72
---

### **Typically R Shiny Job Posting**

Appsilon is an ambitious and fast-growing software house and consultancy
specializing in actions support systems and machine learning with
Fortune 500 clients across the globe. We are a unique company inspired
by a mission to improve our society and environment.

We are a global leader in R and Shiny, which are used by companies of
all sizes to build data applications. When companies run into difficult
problems or want to initiate large-scale enterprise projects, they come
to Appsilon.

Before you apply, please read our [code of
conduct](https://appsilon.com/code-of-conduct/).

Every few months we start completely new projects and dive into a
completely new world. One day we learn the secrets of promotions in
retail chains, another day we analyze satellite images, and then we get
super interesting data from the residential market for analysis. Our
projects are not only an opportunity to test our skills in difficult
statistical, algorithmic, and technological problems but also an
opportunity to learn how many different industries work from the inside.

Tech Stack that you can expect in Appsilon: R, Shiny, JavaScript,
React.js, Python, Docker, Git, AWS, HTML, CSS/ Sass

We are growing fast and that's why we are now looking for a new R/Shiny
Developer to join our team.

#### **Your tasks:** 

-   Experience in building advanced Shiny apps, especially for large
    customers.

-   Understanding of limitations of R and Shiny and proposing ideas on
    how to overcome them. You should have knowledge of advanced
    mechanisms of Shiny (e.g.
    [bindings](https://connect.thinkr.fr/js4shinyfieldnotes/custom-inputs-binding.html),
    register DataObj, performance,
    [promises](https://rstudio.github.io/promises/articles/promises_06_shiny.html),
    [single-threading](https://engineering-shiny.org/optimizing-shiny-code.html#asynchronous-in-shiny),
    etc.) and effectively use it in practice.

-   Knowledge of how to scale Shiny to 1000s concurrent users.
    Contribution to performance optimization on different levels
    (frontend, backend, infrastructure). Understands the way Shiny uses
    WebSockets.

-   Experience in implementing visually impressive apps independently
    from a Graphic Designer

-   Experience in extending Shiny apps with advanced functionalities
    e.g. using custom bindings, JS events in Shiny, JS-Shiny
    communication, Web Components, etc.

-   Experience in delivering solutions known for high quality thanks to
    well balanced test pyramid.

-   Fluent written and verbal communication in English.

#### **What we expect from you:** 

-   Experience in building web applications or websites using R/Shiny or
    JavaScript or Python

-   Implementing visually attractive apps based on the input from the
    UX/UI Designer

-   Experience in using unit testing as a natural technique for
    improving your code structure. Automates other tests such as
    end-to-end or performance tests

-   Fluent written and verbal communication in English

-   You have a valid passport or ID Card

#### **What's in it for you:** 

-   From 7000 up to 22.000 PLN/month +VAT on a B2B contract (\$1600 -
    \$4900 USD/month).

-   26 days of paid holidays + an equivalent of public holidays in
    Poland, est. 11 days in 2022 +5% of salary in Professional
    Development Budget to spend on activities that help you grow

-   33 days (paid 80%) per year on B2B when on a sick leave 4 paid days
    per year to be used for training/conferences, events, or workshops
    Remote work-first working culture with flexible working hours to
    adjust to your family life

-   Private health care insurance for you and your family Life insurance
    for you and your family

-   FitProfit or FitSport membership card (in Poland)

-   AskHenry -- a personal assistant works great in large Polish cities,
    elsewhere limited to online support

-   Opportunity to work with the prestigious brands where you can see
    how data science is used

-   Opportunity to develop yourself as an independent Shiny expert in a
    data science community
